# -*- coding: utf-8 -*-
"""devops class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nk152TYNTQipGyeLwUiBWo6UqSdBEXoj
"""

n=int(input())
if n%3==0 or '3' in str(n):
  print('Jugs')
elif n%5==0 or '5' in str(n):
  print('Mugs')
elif n%7==0 or '7' in str(n):
  print('Pugs')
else:
  print(n)

n=int(input())
if n%3==0 and n%5==0 and n%7==0:
  print('JugsMugsPugs')
elif n%3==0 and n%5==0:
  print('JugsMugs')
elif n%3==0 and n%7==0:
  print('JugsPugs')
elif n%5==0 and n%7==0:
  print('MugsPugs')
elif n%3==0:
  print('Jugs')
elif n%5==0:
  print('Mugs')
elif n%7==0:
  print('Pugs')

n=int(input())
list1=[3,5,7]
list2=['Jugs','Mugs','Pugs']
for i in list1:
  if n%i==0:
    a=list1.index(i)
    print(list2[a],end=" ")

n=int(input())
if n%3==0 and n%5==0 and n%7==0:
  print('JugsMugsPugs')
elif n%3==0 and n%5==0:
  print('JugsMugs')
elif n%3==0 and n%7==0:
  print('JugsPugs')
elif n%5==0 and n%7==0:
  print('MugsPugs')
elif n%3==0:
  print('Jugs')
elif n%5==0:
  print('Mugs')
elif n%7==0:
  print('Pugs')

